# Generated by Django 5.2.9 on 2026-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_external_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number (KYC)', max_length=50, null=True, unique=True),
        ),
    ]
