# Generated by Django 5.2.9 on 2026-01-01 10:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_approved_user_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number (14 characters)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14}$', message='NIN must be exactly 14 alphanumeric characters')]),
        ),
    ]
