# Generated by Django 5.2.9 on 2026-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, null=True),
        ),
    ]
