# Generated by Django 5.2.9 on 2026-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Free trial period in days from user registration'),
        ),
    ]
