# Generated by Django 5.2.9 on 2026-01-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_platformconfig_trial_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='RiderAvailabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('went_online_at', models.DateTimeField()),
                ('went_offline_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
