# Generated by Django 4.2.11 on 2026-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_device_type_alter_user_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('RODIE', 'Rodie'), ('MECHANIC', 'Mechanic'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
