# Generated by Django 5.2.9 on 2026-01-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='mechanic_transition_documents',
            field=models.JSONField(default=list, help_text="List of required documents for mechanic transition, e.g. ['ID', 'License', 'Certificate']"),
        ),
    ]
