# Generated by Django 4.2.11 on 2026-01-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_platformconfig_mechanic_transition_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_login_id',
            field=models.UUIDField(blank=True, help_text='Used to enforce single device login', null=True),
        ),
    ]
