# Generated by Django 5.2.9 on 2026-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_current_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('RIDER', 'Rider'), ('RODIE', 'Rodie'), ('MECHANIC', 'Mechanic')], max_length=10, null=True),
        ),
    ]
