# Generated by Django 5.2.9 on 2026-04-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0008_add_cancellation_models'),
        ('service_requests', '0008_add_rating_fields'),
        ('service_requests', '0026_rating'),
    ]

    operations = [
    ]
