# Generated by Django 6.0 on 2025-12-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BATTERY', 'Battery Jumpstarting'), ('TOWING', 'Car Towing'), ('FLAT_TYRE', 'Flat Tyre Assistance'), ('FUEL', 'Out of Fuel Delivery')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RodieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodie', models.ForeignKey(limit_choices_to={'role': 'RODIE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'unique_together': {('rodie', 'service')},
            },
        ),
    ]
