# Generated by Django 5.2.9 on 2025-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_rodieservice_id_alter_servicetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
