# Generated by Django 5.2.9 on 2026-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rodieservice_created_at_rodieservice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
