# Generated by Django 4.2.11 on 2026-01-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_servicetype_fixed_price_servicetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('MECHANIC', 'Mechanic')], default='BASIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='rodieservice',
            name='rodie',
            field=models.ForeignKey(limit_choices_to={'role__in': ['RODIE', 'MECHANIC']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
