# Generated by Django 5.2.9 on 2026-01-07 07:19

import django.db.models.deletion
import images.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="User's external ID (R001, BS001, etc.)", max_length=10)),
                ('image_type', models.CharField(choices=[('PROFILE', 'Profile Picture'), ('NIN_FRONT', 'NIN Front'), ('NIN_BACK', 'NIN Back'), ('LICENSE', 'License'), ('VEHICLE', 'Vehicle'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('original_image', models.ImageField(storage=images.models.UserImageStorage(), upload_to='temp_uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=images.models.UserImageStorage(), upload_to='temp_thumbnails/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_id', 'image_type'], name='images_user_externa_3eb268_idx'), models.Index(fields=['external_id', 'status'], name='images_user_externa_731eea_idx')],
            },
        ),
    ]
