# Generated by Django 6.0 on 2025-12-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('STARTED', 'Service Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('rider_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rider_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_requests', to=settings.AUTH_USER_MODEL)),
                ('rodie', models.ForeignKey(blank=True, limit_choices_to={'role': 'RODIE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodie_requests', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype')),
            ],
        ),
    ]
