# Generated by Django 5.2.9 on 2026-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_servicerequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='fee_charged',
            field=models.BooleanField(default=False),
        ),
    ]
