# Generated by Django 5.2.9 on 2026-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_servicerequest_fee_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
