# Generated by Django 5.2.9 on 2026-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_servicerequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('STARTED', 'Service Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='REQUESTED', max_length=20),
        ),
    ]
