# Generated by Django 5.2.9 on 2026-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_servicerequest_status'),
    ]

    operations = [
    ]
