# Generated by Django 5.2.9 on 2026-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rider_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating given by rider (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ROADIE_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating given by roadie (1-5)', null=True),
        ),
    ]
