# Generated by Django 5.2.9 on 2026-04-20 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_add_rating_fields'),
        ('requests', '0027_merge_0008_add_cancellation_models_0026_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='requests_ra_service_c01108_idx',
            old_name='requests_ra_service_idx',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='requests_ra_rated_u_58b232_idx',
            old_name='requests_ra_rated_u_idx',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='ROADIE_rating',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rider_rating',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('STARTED', 'Service Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='requests.servicerequest'),
        ),
    ]
