from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import RegisterView, MeView, MyWalletView, MyReferralsView, RoadieStatusUpdateView, PlatformConfigView, NotificationListCreateView, NotificationRUDView, DepositView, WithdrawView, PesapalIPNView
from .tokens import CustomTokenObtainPairView, RiderLoginView, RoadieLoginView
from .admin_views import (
    RiderListCreateView,
    RiderRetrieveUpdateDestroyView,
    RoadieListCreateView,
    RoadieRetrieveUpdateDestroyView,
    RealtimeRidersView,
    AdminListCreateView,
    AdminRetrieveUpdateDestroyView,
    AdminDeletedUsersView,
    AdminRestoreUserView,
    AdminNotificationListCreateView,
    AdminNotificationRUDView,
    AdminRegisterView,
    AdminWalletListCreateView,
    AdminWalletRUDView,
    AdminReferralListCreateView,
    AdminReferralRUDView,
    AdminPlatformConfigView,
    AdminUserPasswordView,
)
from services.admin_views import (
    ServiceTypeListCreateView,
    ServiceTypeRetrieveUpdateDestroyView,
    RodieServiceListCreateView,
    RodieServiceRetrieveUpdateDestroyView,
)
from services.views import RodieMyServicesView
from requests.admin_views import (
    ServiceRequestListCreateView,
    ServiceRequestRetrieveUpdateDestroyView,
    RealtimeRiderLocationsView,
    RealtimeRiderMapView,
    ServiceRequestRouteView,
    AdminAssignRodieView,
)
from locations.admin_views import (
    RealtimeLocationsView,
    RealtimeLocationsMapView,
)
from .admin_auth import AdminTokenObtainPairView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('login/rider/', RiderLoginView.as_view(), name='rider_login'),
    path('login/roadie/', RoadieLoginView.as_view(), name='roadie_login'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('me/', MeView.as_view(), name='me'),
    path('wallet/', MyWalletView.as_view(), name='my_wallet'),
    path('wallet/deposit/', DepositView.as_view(), name='wallet_deposit'),
    path('wallet/withdraw/', WithdrawView.as_view(), name='wallet_withdraw'),
    path('payments/pesapal/ipn/', PesapalIPNView.as_view(), name='pesapal_ipn'),
    path('referrals/', MyReferralsView.as_view(), name='my_referrals'),
    path('roadie/status/', RoadieStatusUpdateView.as_view(), name='roadie_status_update'),
    path('auth/platform/config/', PlatformConfigView.as_view(), name='platform_config'),
    path('notifications/', NotificationListCreateView.as_view(), name='my_notifications'),
    path('notifications/<int:pk>/', NotificationRUDView.as_view(), name='my_notifications_rud'),
    path('auth/admin/login/', AdminTokenObtainPairView.as_view(), name='admin_login'),
    path('auth/admin/register/', AdminRegisterView.as_view(), name='admin_register'),
    path('auth/admin/riders/', RiderListCreateView.as_view(), name='admin_riders_list_create'),
    path('auth/admin/riders/<int:pk>/', RiderRetrieveUpdateDestroyView.as_view(), name='admin_riders_rud'),
    path('auth/admin/roadies/', RoadieListCreateView.as_view(), name='admin_roadies_list_create'),
    path('auth/admin/roadies/<int:pk>/', RoadieRetrieveUpdateDestroyView.as_view(), name='admin_roadies_rud'),
    path('auth/admin/riders/realtime/', RealtimeRidersView.as_view(), name='admin_riders_realtime'),
    path('auth/admin/users/', AdminListCreateView.as_view(), name='admin_users_list_create'),
    path('auth/admin/users/<int:pk>/', AdminRetrieveUpdateDestroyView.as_view(), name='admin_users_rud'),
    path('auth/admin/users/deleted/', AdminDeletedUsersView.as_view(), name='admin_users_deleted'),
    path('auth/admin/users/<int:pk>/restore/', AdminRestoreUserView.as_view(), name='admin_user_restore'),
    path('auth/admin/services/', ServiceTypeListCreateView.as_view(), name='admin_services_list_create'),
    path('auth/admin/services/<int:pk>/', ServiceTypeRetrieveUpdateDestroyView.as_view(), name='admin_services_rud'),
    path('auth/admin/rodie-services/', RodieServiceListCreateView.as_view(), name='admin_rodie_services_list_create'),
    path('auth/admin/rodie-services/<int:pk>/', RodieServiceRetrieveUpdateDestroyView.as_view(), name='admin_rodie_services_rud'),
    path('rodie/services/', RodieMyServicesView.as_view(), name='rodie_my_services'),
    path('auth/admin/requests/', ServiceRequestListCreateView.as_view(), name='admin_requests_list_create'),
    path('auth/admin/requests/<int:pk>/', ServiceRequestRetrieveUpdateDestroyView.as_view(), name='admin_requests_rud'),
    path('auth/admin/requests/realtime/', RealtimeRiderLocationsView.as_view(), name='admin_requests_realtime'),
    path('auth/admin/requests/realtime/map/', RealtimeRiderMapView.as_view(), name='admin_requests_realtime_map'),
    path('auth/admin/requests/<int:pk>/route/', ServiceRequestRouteView.as_view(), name='admin_request_route'),
    path('auth/admin/locations/realtime/', RealtimeLocationsView.as_view(), name='admin_locations_realtime'),
    path('auth/admin/locations/realtime/map/', RealtimeLocationsMapView.as_view(), name='admin_locations_realtime_map'),
    path('auth/admin/wallets/', AdminWalletListCreateView.as_view(), name='admin_wallets_list_create'),
    path('auth/admin/wallets/<int:pk>/', AdminWalletRUDView.as_view(), name='admin_wallets_rud'),
    path('auth/admin/referrals/', AdminReferralListCreateView.as_view(), name='admin_referrals_list_create'),
    path('auth/admin/referrals/<int:pk>/', AdminReferralRUDView.as_view(), name='admin_referrals_rud'),
    path('auth/admin/platform/config/', AdminPlatformConfigView.as_view(), name='admin_platform_config'),
    path('auth/admin/notifications/', AdminNotificationListCreateView.as_view(), name='admin_notifications_list_create'),
    path('auth/admin/notifications/<int:pk>/', AdminNotificationRUDView.as_view(), name='admin_notifications_rud'),
    path('auth/admin/users/<int:pk>/password/', AdminUserPasswordView.as_view(), name='admin_user_password_change'),
    path('auth/admin/requests/<int:pk>/assign/', AdminAssignRodieView.as_view(), name='admin_request_assign'),
]
