# Generated by Django 4.2.11 on 2026-01-27 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Garage name as publicly displayed', max_length=255)),
                ('garage_type', models.CharField(choices=[('INDIVIDUAL', 'Individual / Informal'), ('REGISTERED', 'Registered Business')], max_length=20)),
                ('years_in_operation', models.PositiveIntegerField()),
                ('physical_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operating_hours', models.JSONField(help_text="Operating hours per day, e.g. {'monday': '08:00-17:00'}")),
                ('primary_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('business_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_national_id', models.CharField(max_length=20, unique=True)),
                ('owner_id_front', models.ImageField(blank=True, null=True, upload_to='garage_docs/')),
                ('owner_id_back', models.ImageField(blank=True, null=True, upload_to='garage_docs/')),
                ('owner_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('owner_email', models.EmailField(max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_registration_cert', models.FileField(blank=True, null=True, upload_to='garage_docs/')),
                ('tin_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('trading_license', models.FileField(blank=True, null=True, upload_to='garage_docs/')),
                ('local_authority_letter', models.FileField(blank=True, null=True, upload_to='garage_docs/')),
                ('exterior_photo', models.ImageField(upload_to='garage_photos/')),
                ('interior_workshop_photo', models.ImageField(upload_to='garage_photos/')),
                ('tools_equipment_photo', models.ImageField(blank=True, null=True, upload_to='garage_photos/')),
                ('workshop_video', models.FileField(blank=True, null=True, upload_to='garage_videos/')),
                ('vehicle_types', models.JSONField(help_text='List of supported vehicle types')),
                ('services_offered', models.JSONField(help_text='List of services offered')),
                ('services_not_offered', models.JSONField(blank=True, help_text='List of services not offered', null=True)),
                ('pricing_info', models.JSONField(help_text='Pricing details for each service')),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('mechanics_count', models.PositiveIntegerField(default=1)),
                ('lead_mechanic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, help_text='List of certifications', null=True)),
                ('specialized_skills', models.TextField(blank=True, null=True)),
                ('warranty_offered', models.BooleanField(default=False)),
                ('warranty_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_turnaround_hours', models.PositiveIntegerField(help_text='Average service turnaround time in hours')),
                ('emergency_service_available', models.BooleanField(default=False)),
                ('working_days', models.JSONField(help_text="Working days, e.g. ['monday', 'tuesday', ...]")),
                ('cancellation_policy', models.TextField()),
                ('payment_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('provider_name', models.CharField(help_text='Mobile money provider or bank name', max_length=255)),
                ('settlement_preference', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='WEEKLY', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='SUBMITTED', max_length=20)),
                ('submission_completeness', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of completion', max_digits=5)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_garages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarageServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycles'), ('CAR', 'Cars'), ('VAN', 'Vans'), ('TRUCK', 'Trucks')], max_length=20)),
                ('service_category', models.CharField(choices=[('ENGINE_REPAIR', 'Engine Repair'), ('BRAKE_SERVICE', 'Brake Service'), ('ELECTRICAL_DIAGNOSTICS', 'Electrical & Diagnostics'), ('TIRE_WHEEL', 'Tire & Wheel Services'), ('BODY_WORK', 'Body Work & Painting'), ('ROUTINE_SERVICING', 'Routine Servicing'), ('ACCIDENT_REPAIR', 'Accident Repair')], max_length=30)),
                ('description', models.TextField(help_text='Description of the mechanical issue')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='garages.garage')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
