# Generated by Django 4.2.11 on 2026-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='workshop_video',
        ),
        migrations.AddField(
            model_name='garage',
            name='application_tracking_id',
            field=models.CharField(blank=True, help_text='Unique tracking ID for application status checking', max_length=10, null=True, unique=True),
        ),
    ]
